### ISSUE TITLE
Custom detector with CPU layers

### ISSUE THREAD

**Issue by BloomBabe** [Xilinx/smartcam#5] opened 2022-10-11 10:31 UTC
Am I right, that Smartcam doesnt work with custom detectors, if it have CPU layers aftter compilation, not only DPU supported layers?

**Comment by xlnx-yuxiz** [comment] 2022-10-18 03:18
I think that you are talking about customizing with a different AI model which doesn't only have DPU layers but also CPU layers. 
Since currently smartcam only support limited classes of Vitis AI models: "YOLOV3, FACEDETECT, CLASSIFICATION, SSD,REFINEDET, TFSSD, YOLOV2", so for your AI model which is not inherently supported by Vitis AI library, yes, it needs much more customization work to enable it in this app, which is not the easy customization way what we provided.

**Comment by BloomBabe** [comment] 2022-10-18 09:13
> 

I had yolov3 model with mobilenetv2 backbone and tried to integrate it to Smartcam. In Vitis AI 1.4 some layers are not DPU supported and Smartcam didn't work with that model. But with Darknet Yolov3 it works fine, so I think the reason is not supported DPU layers.

**Comment by xlnx-yuxiz** [comment] 2022-10-18 15:34
Yes, that's the cause. Can we close this issue now?

**Closed as completed** 2022-10-20 12:59 UTC
